2025-02-16 09:09:02,208 | WARNING | Incorrect type for runner name
Traceback (most recent call last):
  File "C:\Users\Александр\PycharmProjects\PythonDeveloper---UrbanUnivercity\UnitTests\RunnerTest.py", line 29, in test_run
    my_runner = rt.Runner(2, 7)
  File "C:\Users\Александр\PycharmProjects\PythonDeveloper---UrbanUnivercity\UnitTests\runner_and_tournament.py", line 6, in __init__
    raise TypeError(f'Имя может быть только строкой, передано {type(name).__name__}')
TypeError: Имя может быть только строкой, передано int
2025-02-16 09:09:02,214 | WARNING | Incorrect speed value for runner
Traceback (most recent call last):
  File "C:\Users\Александр\PycharmProjects\PythonDeveloper---UrbanUnivercity\UnitTests\RunnerTest.py", line 18, in test_walk
    my_runner = rt.Runner('Bolt', -5)
  File "C:\Users\Александр\PycharmProjects\PythonDeveloper---UrbanUnivercity\UnitTests\runner_and_tournament.py", line 11, in __init__
    raise ValueError(f'Скорость не может быть отрицательной, сейчас {speed}')
ValueError: Скорость не может быть отрицательной, сейчас -5
